# Generated by Django 4.0.4 on 2022-05-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commented',
            new_name='commentedPost',
        ),
    ]
