# Generated by Django 4.0.4 on 2022-05-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_postmodel_likecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
