# Generated by Django 4.0.4 on 2022-05-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_comments_commentedpost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followmodel',
        ),
    ]
